
package hr.infomare.cop.app;

import hr.infomare.cop.opci.Pomocna;
import hr.infomare.cop.app.*;

import java.awt.CardLayout;

/**
 *
 * @author ivanj
 */
public class Login extends javax.swing.JPanel {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        btnSpremi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtServer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKorisnik = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JPasswordField();
        btnOdustani = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(255, 125));
        setMinimumSize(new java.awt.Dimension(255, 125));
        setPreferredSize(new java.awt.Dimension(307, 134));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSpremi.setText("Spremi");
        btnSpremi.setMaximumSize(new java.awt.Dimension(77, 21));
        btnSpremi.setMinimumSize(new java.awt.Dimension(77, 21));
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });
        add(btnSpremi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 77, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Server");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtServer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtServer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtServer.setMaximumSize(null);
        add(txtServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 154, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Korisnièko ime");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Lozinka");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtKorisnik.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtKorisnik.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtKorisnik.setMaximumSize(new java.awt.Dimension(4, 19));
        add(txtKorisnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 154, -1));

        txtLozinka.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        add(txtLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 154, -1));

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });
        add(btnOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));
    }//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        // TODO add your handling code here:
        
        Pomocna.spremiPostavke(txtServer.getText(), txtKorisnik.getText(), txtLozinka.getText());
        
        if (Pomocna.postavkeIspravne()){
            Run.promijeniCard("Forma");
        } else Pomocna.porukaError(this,"Postavke nisu ispravne !");
    }//GEN-LAST:event_btnSpremiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSpremi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKorisnik;
    private javax.swing.JPasswordField txtLozinka;
    private javax.swing.JTextField txtServer;
    // End of variables declaration//GEN-END:variables

}
