
package hr.infomare.cop.app;

import hr.infomare.cop.opci.Aes;

import java.util.HashMap;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;

import javax.persistence.Persistence;

import hr.infomare.cop.db.*;

import java.math.BigDecimal;

import java.util.BitSet;
import java.util.Date;

import javax.swing.DefaultListModel;
import javax.swing.SwingWorker;

import org.eclipse.persistence.config.PersistenceUnitProperties;


/**
 *
 * @author ivanj
 */
public class Forma_old extends javax.swing.JFrame {


    private HashMap getPersistenceProps() {
        HashMap hm = new HashMap();
        hm.put(PersistenceUnitProperties.JDBC_USER, "COPUSER");
        hm.put(PersistenceUnitProperties.JDBC_PASSWORD, "coppass");
        hm.put(PersistenceUnitProperties.JDBC_URL, "jdbc:as400://s655cb5b.infomare.hr;");

        return hm;
    }


    class Task extends SwingWorker<Void, Void> {

        @Override
        public Void doInBackground() {

            jProgressBar1.setStringPainted(true); // da prikaze postotak progressa
            jProgressBar1.setMinimum(0);
            jProgressBar1.setMaximum(99);


            EntityManagerFactory emf =
                Persistence.createEntityManagerFactory("infomare-cop-import-klijent", getPersistenceProps());
            EntityManager em = emf.createEntityManager();

            try {
                em.getTransaction().begin();

                // èitanje xml-a i insert podataka

                System.out.println("pocetak");
                /*
                 Zaposl z= new Zaposl();
                 z.setObrid(1);
                 z.setRbr(1);
                 z.setOib("2312312");
                 z.setIme("ime");
                 z.setPrezime("prez");
                 z.setAdresa("adr");
                 z.setInternauj("aa");
                 z.setNazivoj("naziv oj");
                 z.setDatumisp(new Date());
                 z.setBruto(1L);
                 z.setDopriz(2L);
                 z.setDohodak(3L);
                 z.setOlaksica(4L);
                 z.setPorezosn(5L);
                 z.setPoripri(5L);
                 z.setNeto(6L);
                 z.setNeoporez(7L);
                 z.setPrimanja(8L);
                 z.setObustave(9L);
                 z.setIsplata(10L);
                 z.setTrosakpl(11L);

                 em.persist(z);

                */

                Olaksica o = new Olaksica(new BigDecimal("1"), new BigDecimal("2"), "test", 3, 5, 6, 7);

                /*
                 o.setObrid(1);
                 o.setRbr(1);
                 o.setStv(1);
                 o.setOlaksica(3);
                 o.setNaziv("aa");
                 o.setKoeficijent(new BigDecimal("2"));
                 o.setIznos(new BigDecimal("3"));
                 */
                em.persist(o);

                System.out.println("kraj");


                em.getTransaction().commit();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                em.close();
            }

            return null;
        }
    }


    /** Creates new form Forma */
    public Forma_old() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            jTextField1.setText(Aes.encrypt("test"));
            Task t = new Task();
            t.execute();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forma_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forma_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forma_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forma_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forma_old().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
